customers/urls.py
from django.urls import path

from customers.views import ShowCustomers, AddCustomer, DeleteCustomer

app_name = "customers"

urlpatterns = [
    path('', ShowCustomers.as_view(), name='customers-list'),
    path('add/', AddCustomer.as_view(), name='add-customer'),
    path('<int:id>/delete/', DeleteCustomer.as_view(), name='delete-customer'),
]

misitio/urls.py
from django.contrib import admin
from django.urls import path, include

from homepage.views import Main

urlpatterns = [
    path('', Main.as_view(), name="main"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls',namespace="user")),
    path('homepage/', include('homepage.urls',namespace="homepage")),
    path('sales/', include('sales.urls',namespace="sales")),
    path('articles/', include('articles.urls',namespace="articles")),
    path('customers/', include('customers.urls',namespace="customers")),

]

user/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import MyLoginView

app_name="user"
urlpatterns=[
    path('login/', MyLoginView.as_view(), name="login"),
    path('logout/', login_required(LogoutView.as_view()), name="logout")

]

customers/models.py
from django.db import models
codigo_cliente=1

class Customer(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, editable=True, verbose_name='Nombre/s')
    surname = models.CharField(max_length=255, null=False, blank=False, editable=True, verbose_name='Apellido/s')

    class Meta:
        ordering = ['name']
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    def __str__(self):
        return self.name


class Clientes(models.Model):
    GENERAL = 'G'
    REDUCIDO = 'R'
    SUPERREDUCIDO = 'S'
    EXENTO = 'E'
    choices = [
        (GENERAL, 'General'),
        (REDUCIDO, 'Reducido'),
        (SUPERREDUCIDO, 'Superreducido'),
        (EXENTO, 'Exento')
    ]
    credito_maximo = models.FloatField(null=True, blank=True, default=0)
    estado_cliente = models.BooleanField(verbose_name='Estado de cliente')
    tipo_cliente = models.CharField(max_length=1, verbose_name='Tipo de cliente')
    categoria_iva = models.CharField(max_length=1, choices=choices, verbose_name='Categoria IVA', unique=True, null=False)
    telefono = models.TextField(verbose_name='Telefono')
    cuit = models.TextField(verbose_name='CUIT', unique=True)
    e_mail = models.TextField(verbose_name='e-mail')
    codigo_postal = models.IntegerField(verbose_name='Codigo postal')
    fecha_nac = models.DateTimeField(null=True, editable=True, verbose_name='Fecha del nacimiento')
    nombre = models.TextField(verbose_name='Nombre')
    piso = models.IntegerField(verbose_name="Piso")
    departamento = models.CharField(max_length=20, verbose_name="Departamento")
    calle = models.TextField(verbose_name='Calle')
    numero = models.IntegerField(verbose_name='Numero')
    codigo = models.IntegerField(verbose_name='Codigo de cliente', unique=True)
    fecha_cre = models.DateTimeField(null=True, editable=True, verbose_name='Fecha de Creacion')

    def __init__(self):
        global codigo_cliente
        self.codigo = codigo_cliente
        codigo_cliente += 1

    class Meta:
        ordering= ["cuit"]
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

customers/forms.py
from django import forms

from customers.models import Clientes, Customer


class CustomerForm(forms.ModelForm):
    name = forms.CharField( widget= forms.TextInput(attrs={'placeholder':'Nombre/s...'}), label=False)
    surname = forms.CharField( widget= forms.TextInput(attrs={'placeholder':'Apellido/s...'}), label=False)
    class Meta:
        model = Customer
        fields = ['name', 'surname']

customers/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView, CreateView, DeleteView

from customers.forms import CustomerForm
from customers.models import Clientes, Customer


class ShowCustomers(ListView):
    model = Customer
    template_name = "clientes_list.html"
    paginate_by = 20
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class AddCustomer(CreateView):
    model = Customer
    #fields = ['name']
    template_name = 'cliente_add.html'
    form_class = CustomerForm
    success_url = reverse_lazy('customers:customers-list')

class DeleteCustomer(DeleteView):
    template_name = 'cliente_delete.html'
    success_url = reverse_lazy('customers:customers-list')
    def get_object(self):
        id_ = self.kwargs.get('id')
        return get_object_or_404(Customer, id=id_)

customers/templates/cliente_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clientes</title>
</head>
<body>
    <h1>Agregar Nuevo Cliente</h1>

    <form method="POST" enctype="multipart/form-data">

        <!-- Security token -->
        {% csrf_token %}

        <!-- Using the formset -->
        {{ form.as_p }}

        <input type="submit" value="Cargar Cliente">
    </form>

</body>
</html>

customers/templates/cliente_delete.html
<form action="." method="post">
    {% csrf_token %}
    <h1>¿Desea eliminar al cliente: {{ object.name }}?</h1>
    <p>
        <input type="submit" value="Si"/>
        <a href="{% url 'customers:customers-list' %}">
            Cancelar
        </a>
    </p>

</form>

customers/templates/clientes_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Clientes</title>
</head>
<body>
    <h1>Clientes</h1>
    <a href="{% url 'customers:add-customer' %}">Cargar Nuevo Cliente</a>
    <ul>

        {% for cliente in object_list %}
            <li>
                <div style="background-color: #00b44e">
                    {{ cliente.name }}
                    <a href="{% url 'customers:delete-customer' cliente.id %}">Eliminar</a>
                </div>
            </li>
        {% empty %}
            <li>No hay clientes aún.</li>
        {% endfor %}

    </ul>
</body>
</html>